#!/usr/bin/env bash
# P3.16: release manifest. A `releases/<version>.yaml` file records a
# KNOWN-GOOD, VALIDATED combination of the whole stack — every component
# version, the host runtimes it was tested on, which capabilities probed
# pass, and the benchmark outcome. It is what makes the stack reproducible:
# on a fresh VPS, `scripts/install.sh --release <version>` + authenticate +
# `agent doctor` gives you the same environment. No LLM. Sourced by
# bin/agent and scripts/install.sh. Must not be executed directly.
set -euo pipefail

_RELEASE_LIB_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
_RELEASE_ROOT_DIR="$(cd "$_RELEASE_LIB_DIR/.." && pwd)"

# AGENT_RELEASES_DIR (tests) overrides where manifests live. Evaluated at
# call time so a test can set it after sourcing.
release_dir() { printf '%s' "${AGENT_RELEASES_DIR:-$_RELEASE_ROOT_DIR/releases}"; }
release_path() { printf '%s/%s.yaml\n' "$(release_dir)" "$1"; }

release_list() {
  local d; d="$(release_dir)"
  local f found=0
  if [ -d "$d" ]; then
    for f in "$d"/*.yaml; do [ -f "$f" ] || continue; found=1; basename "$f" .yaml; done
  fi
  [ "$found" -eq 1 ] || echo "no releases defined yet"
}

release_latest() {
  local d; d="$(release_dir)"
  [ -d "$d" ] || return 0
  ls -1 "$d"/*.yaml 2>/dev/null | sed 's|.*/||; s|\.yaml$||' | sort -V | tail -1
}

# release_create <version> [--benchmark-offline pass|fail|not-run]
# Snapshots the CURRENT inventory + capability verdicts into a manifest.
# Never fabricates a live-benchmark result (records "not-run" unless told).
release_create() {
  local version="$1" bench_offline="not-run" bench_live="not-run"
  shift || true
  while [ $# -gt 0 ]; do
    case "$1" in
      --benchmark-offline) bench_offline="$2"; shift 2 ;;
      --benchmark-live) bench_live="$2"; shift 2 ;;
      *) shift ;;
    esac
  done
  [ -n "$version" ] || { echo "usage: release_create <version>" >&2; return 2; }
  mkdir -p "$(release_dir)"
  local out; out="$(release_path "$version")"

  {
    echo "# P3.16 release manifest — a known-good, validated stack combination."
    echo "# Generated by 'agent' from the live inventory; edit only to correct facts."
    echo "release:"
    echo "  stack_version: \"$version\""
    echo "  created_at: \"$(date -u +%Y-%m-%dT%H:%M:%SZ)\""
    echo "  repo_commit: \"$(git -C "$_RELEASE_ROOT_DIR" rev-parse HEAD 2>/dev/null || echo unknown)\""
    echo
    echo "components:"
    local component installed
    while IFS= read -r component; do
      [ -n "$component" ] || continue
      installed="$(inventory_detect_version "$component")"
      echo "  $component: \"${installed:-MISSING}\""
    done < <(compat_components)
    echo
    echo "tested_on:"
    echo "  os: \"$(uname -s 2>/dev/null || echo unknown) $(uname -r 2>/dev/null || echo '')\""
    echo "  node: \"$(inventory_detect_version node)\""
    echo "  python: \"$(inventory_detect_version python)\""
    echo
    echo "capabilities:"
    while IFS= read -r component; do
      compat_is_critical "$component" || continue
      echo "  $component: \"$(capability_verdict "$component")\""
    done < <(compat_components)
    echo
    echo "benchmark:"
    echo "  deterministic: \"$bench_offline\""
    echo "  live: \"$bench_live\""
  } > "$out"

  echo "release manifest written: $out"
  printf '%s\n' "$version"
}

release_show() {
  local version="${1:-$(release_latest)}"
  [ -n "$version" ] || { echo "no releases defined" >&2; return 1; }
  local f; f="$(release_path "$version")"
  [ -f "$f" ] || { echo "error: no such release: $version" >&2; return 1; }
  cat "$f"
}

# release_verify [version]
# Compares the CURRENT machine against a release manifest: component
# versions, critical capability verdicts, and the offline benchmark.
# Prints a report; returns nonzero on any mismatch.
release_verify() {
  local version="${1:-$(release_latest)}"
  local f; f="$(release_path "$version")"
  [ -f "$f" ] || { echo "error: no such release: $version" >&2; return 1; }
  echo "verifying this machine against release $version ($f)"

  local mismatch=0 component want got
  while IFS= read -r component; do
    [ -n "$component" ] || continue
    want="$(policy_get "$f" components "$component" "")"
    [ -n "$want" ] || continue
    got="$(inventory_detect_version "$component")"
    got="${got:-MISSING}"
    if [ "$want" = "$got" ]; then
      echo "  ok   $component = $got"
    else
      echo "  DIFF $component: release wants $want, machine has $got"
      mismatch=1
    fi
  done < <(compat_components)

  while IFS= read -r component; do
    compat_is_critical "$component" || continue
    want="$(policy_get "$f" capabilities "$component" "")"
    got="$(capability_verdict "$component")"
    if [ -n "$want" ] && [ "$want" != "$got" ]; then
      echo "  CAP  $component: release recorded $want, now probes $got"
      [ "$got" = "INCOMPATIBLE" ] && mismatch=1
    fi
  done < <(compat_components)

  if command -v benchmark_suite >/dev/null 2>&1; then
    if benchmark_suite --offline >/dev/null 2>&1; then
      echo "  ok   offline benchmark passes"
    else
      echo "  FAIL offline benchmark does not pass on this machine"
      mismatch=1
    fi
  fi

  if [ "$mismatch" -eq 0 ]; then
    echo "RELEASE_VERIFIED: this machine matches release $version."
    return 0
  fi
  echo "RELEASE_MISMATCH: this machine does not match release $version (see DIFF/CAP/FAIL lines)."
  return 1
}

# release_pin <version> <component>
# The version scripts/install.sh / scripts/configure.sh should install for a
# reproducible '--release' setup. Empty when the release doesn't pin it.
release_pin() {
  local f; f="$(release_path "$1")"
  [ -f "$f" ] || return 1
  policy_get "$f" components "$2" ""
}
