#!/usr/bin/env bash
# P3.5: `agent update plan [<component>]`. Turns "there is a newer version"
# into a concrete, inspectable plan: what command would run, which configs
# and skills it touches, which capability probes would gate it afterwards,
# how to roll it back, and a DETERMINISTIC risk tier. Makes zero changes and
# zero LLM calls — risk is decided by rules, not a model. Sourced by
# bin/agent. Must not be executed directly.
set -euo pipefail

_UPDATE_PLAN_LIB_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# _plan_semver_bump <from> <to> -> major | minor | patch | none | unknown
_plan_semver_bump() {
  node -e '
    const p = (v) => { const m = /^(\d+)\.(\d+)\.(\d+)/.exec(v || ""); return m ? [+m[1], +m[2], +m[3]] : null }
    const a = p(process.argv[1]), b = p(process.argv[2])
    let out = "unknown"
    if (a && b) {
      if (a[0] !== b[0]) out = "major"
      else if (a[1] !== b[1]) out = "minor"
      else if (a[2] !== b[2]) out = "patch"
      else out = "none"
    }
    process.stdout.write(out)
  ' "$1" "$2"
}

# update_risk <component> <current> <candidate> [staging_available:true|false]
# LOW    a patch bump of a non-critical, non-provider component
# MEDIUM a minor bump of Graphify / Agent-Reach; a claude-mem minor
# HIGH   anything touching dsh / Claude / Codex; a claude-mem MAJOR; any
#        major bump; staging that could not be verified in isolation
update_risk() {
  local component="$1" current="$2" candidate="$3" staging="${4:-true}"
  local bump tier
  bump="$(_plan_semver_bump "$current" "$candidate")"

  case "$component" in
    deepseek-harness|claude-code|codex)
      tier="HIGH" ;;                       # the Claude/Codex flow itself
    claude-mem)
      case "$bump" in
        major) tier="HIGH" ;;              # possible irreversible storage migration
        minor) tier="MEDIUM" ;;
        *) tier="LOW" ;;
      esac ;;
    graphify|agent-reach)
      case "$bump" in
        major) tier="HIGH" ;;
        minor) tier="MEDIUM" ;;
        *) tier="LOW" ;;
      esac ;;
    node|git)
      tier="HIGH" ;;                       # critical runtimes (still operator-driven)
    *)
      case "$bump" in
        major) tier="HIGH" ;;
        minor) tier="MEDIUM" ;;
        *) tier="LOW" ;;
      esac ;;
  esac

  # If we can't even tell what kind of version change this is, we can't
  # assess it — that is HIGH, not a guess.
  if [ "$bump" = "unknown" ] || [ -z "$bump" ]; then
    tier="HIGH"
  fi
  # A candidate we could not verify in an isolated staging environment
  # escalates one tier.
  if [ "$staging" != "true" ] && [ "$staging" != "n/a" ]; then
    case "$tier" in LOW) tier="MEDIUM" ;; MEDIUM) tier="HIGH" ;; esac
  fi
  printf '%s' "$tier"
}

# update_plan_command <component> <candidate>
# The exact command an apply would run (still never run by plan itself).
update_plan_command() {
  local component="$1" candidate="$2" source scheme pkg
  source="$(compat_source "$component")"
  scheme="$(_update_source_scheme "$source")"
  pkg="$(_update_source_pkg "$source")"
  case "$scheme" in
    npm)
      printf 'npm install -g %s@%s' "$pkg" "$candidate" ;;
    bundle)
      local profile="${component#claude-}"
      case "$component" in claude-code) profile="lead" ;; codex) profile="reviewer" ;; esac
      printf 'dsh plugin --profile %s add %s@%s' "$profile" "$pkg" "$candidate" ;;
    pypi)
      if [ "$component" = "graphify" ]; then
        printf 'uv tool install %s==%s  &&  graphify install   # then VERIFY the SKILL.md path' "$pkg" "$candidate"
      else
        printf 'uv tool install %s==%s' "$pkg" "$candidate"
      fi ;;
    *)
      printf '(system component — upgrade %s via the OS package manager; out of `agent update` scope)' "$component" ;;
  esac
}

# update_plan_affected <component> -> one "kind\tpath-or-note" line each
update_plan_affected() {
  local component="$1" dsh_home
  dsh_home="$(env_dsh_home)"
  case "$component" in
    deepseek-harness)
      printf 'config\t%s/profiles/lead/  (regenerated by scripts/configure.sh)\n' "$dsh_home"
      printf 'config\t%s/profiles/reviewer/  (regenerated by scripts/configure.sh)\n' "$dsh_home"
      printf 'config\tthis repo: harness/profiles/*, harness/prompts/*\n' ;;
    claude-code)
      printf 'config\t%s/profiles/lead/package.json\n' "$dsh_home"
      printf 'config\t%s/profiles/lead/cordis.patch.yml\n' "$dsh_home" ;;
    codex)
      printf 'config\t%s/profiles/reviewer/package.json\n' "$dsh_home"
      printf 'config\t%s/profiles/reviewer/cordis.patch.yml\n' "$dsh_home"
      printf 'config\t%s/profiles/reviewer/codex-home/config.toml\n' "$dsh_home" ;;
    claude-mem)
      printf 'config\t~/.claude-mem/settings.json\n'
      printf 'data\t~/.claude-mem/  (storage — a MAJOR upgrade may migrate this irreversibly)\n'
      printf 'plugin\tClaude Code plugin registration (npx claude-mem install)\n' ;;
    graphify)
      printf 'skill\t~/.claude/skills/graphify/SKILL.md  (verify the real path after install)\n'
      printf 'config\t~/.claude/CLAUDE.md graphify section + PreToolUse hook\n' ;;
    agent-reach)
      printf 'skill\t~/.claude/skills/agent-reach/SKILL.md  (explicit refresh only)\n' ;;
    *)
      printf 'none\t(system component)\n' ;;
  esac
}

# update_plan_for <component>
# Emits a stable set of "key: value" / "  - ..." lines for one component,
# consumed by update_plan_print (human) and update_plan_json.
update_plan_for() {
  local component="$1"
  compat_has_component "$component" || { echo "error: unknown component: $component" >&2; return 1; }

  local current candidate source scheme staging risk
  current="$(inventory_detect_version "$component")"
  candidate="$(update_available_version "$component")"
  source="$(compat_source "$component")"
  scheme="$(_update_source_scheme "$source")"

  # Staging feasibility (real check is PHASE 6; here we only know the a-priori
  # answer from the source type + the known Agent-Reach discrepancy).
  staging="true"
  case "$scheme" in system) staging="n/a" ;; esac
  [ "$component" = "agent-reach" ] && staging="false"

  risk="$(update_risk "$component" "$current" "$candidate" "$([ "$staging" = "false" ] && echo false || echo true)")"

  # An irreversible data migration is always HIGH and always caps the
  # rollback promise, regardless of bump size.
  local migration_severity rollback_scope="full"
  migration_severity="$(migration_detect "$component" "$current" "${candidate:-0.0.0}" | sed -n 's/^severity: //p')"
  if [ "$migration_severity" = "irreversible" ]; then
    risk="HIGH"
    rollback_scope="partial — an irreversible data migration cannot be fully undone"
  elif [ "$migration_severity" = "unknown" ]; then
    rollback_scope="uncertain"
  fi

  echo "component: $component"
  echo "current: ${current:-<not installed>}"
  echo "candidate: ${candidate:-<unknown — registry unreachable>}"
  echo "source: $source"
  echo "channel: $(compat_channel "$component")"
  echo "critical: $(compat_is_critical "$component" && echo true || echo false)"
  echo "risk: $risk"
  echo "staging_isolatable: $staging"
  echo "apply_command: $(update_plan_command "$component" "${candidate:-<candidate>}")"
  echo "affected:"
  update_plan_affected "$component" | while IFS=$'\t' read -r kind note; do
    echo "  - [$kind] $note"
  done
  echo "post_update_capability_checks:"
  compat_required_capabilities "$component" | while IFS= read -r cap; do
    [ -n "$cap" ] && echo "  - $cap"
  done
  echo "migration_severity: $migration_severity"
  echo "rollback_scope: $rollback_scope"
  echo "rollback: $(compat_rollback_note "$component")"
  echo "migration_concerns:"
  migration_detect "$component" "$current" "${candidate:-0.0.0}" | sed -n 's/^concern: /  - /p'
  echo "migration_notes: $(compat_migration_notes "$component")"
}

# update_plan_print [<component>]
# With no component: a plan for every component that has an update available.
update_plan_print() {
  local target="${1:-}"
  if [ -n "$target" ]; then
    update_plan_for "$target" || return 1
    echo
    echo "This plan changed nothing. To apply: agent update apply $target"
    return 0
  fi

  local any=0 component installed available scheme status critical
  while IFS=$'\t' read -r component installed available scheme status critical; do
    [ "$status" = "update_available" ] || continue
    any=1
    echo "=============================================================="
    update_plan_for "$component"
    echo
  done < <(update_check)
  if [ "$any" -eq 0 ]; then
    echo "no component has a discoverable update right now (run: agent update check)."
    return 0
  fi
  echo "These plans changed nothing. Apply one at a time: agent update apply <component>"
}

update_plan_json() {
  local target="${1:-}"
  if [ -n "$target" ]; then
    update_plan_for "$target" | node "$_UPDATE_PLAN_LIB_DIR/json-tools.mjs" plan-build
    return $?
  fi
  local component installed available scheme status critical first=1
  printf '['
  while IFS=$'\t' read -r component installed available scheme status critical; do
    [ "$status" = "update_available" ] || continue
    [ "$first" -eq 1 ] || printf ','
    first=0
    update_plan_for "$component" | node "$_UPDATE_PLAN_LIB_DIR/json-tools.mjs" plan-build
  done < <(update_check)
  printf ']'
}
